apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-webapp.fullname" . }}
  labels:
    app: {{ include "python-webapp.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "python-webapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "python-webapp.name" . }}
    spec:
      containers:
        - name: {{ include "python-webapp.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          volumeMounts:
            - name: db-storage
              mountPath: /data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ include "python-webapp.fullname" . }}-pvc

