replicacount: 1

image:
  repository: placeholder  # overridden dynamically by Harness
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30080

persistence:
  enabled: true
  size: 1Gi
  storageClassName: ""

env:
  - name: FLASK_SECRET_KEY
    value: "supersecretkey"
  - name: DB_PATH
    value: "/data/app.db"

resources: {}


